# This is a basic workflow to help you get started with Actions

name: Develop

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "develop" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        id: config
        run: |
          OPENTOFU_VERSION=$(echo $(cat Dockerfile | grep 'ARG OPENTOFU_VERSION=') | cut -d'=' -f2)
          echo "OPENTOFU_VERSION=$(echo $OPENTOFU_VERSION)" >> $GITHUB_ENV
          TERRAGRUNT_VERSION=$(echo $(cat Dockerfile | grep 'ARG TERRAGRUNT_VERSION=') | cut -d'=' -f2)
          echo "TERRAGRUNT_VERSION=$(echo $TERRAGRUNT_VERSION)" >> $GITHUB_ENV
          VERSION="${OPENTOFU_VERSION}-${{ github.run_number }}"
          echo "VERSION=$(echo $VERSION)" >> $GITHUB_OUTPUT
          echo "VERSION=$(echo $VERSION)" >> $GITHUB_ENV

      - name: Show config
        id: show-config
        run: |
          echo "OPENTOFU_VERSION: ${OPENTOFU_VERSION}"
          echo "TERRAGRUNT_VERSION: ${TERRAGRUNT_VERSION}"
          echo "VERSION: ${VERSION}"

      - name: "Build image with tag ${{ env.VERSION }}"
        id: build
        uses: aevea/action-kaniko@v0.14.0
        with:
          tag: ${{ env.VERSION }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
